using DTOs;
using Microsoft.AspNetCore.Mvc;
using SurveyBusinessLayer;

namespace SurveyApplication.Controllers;

[ApiController]
[Route("api/surveys")]
public class SurveyController : ControllerBase
{
    [HttpGet("All", Name = "GetAllSurveys")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<IEnumerable<SurveyTableDto>>> GetAllSurveys()
    {
        var surveys = await SurveyBL.GetAllSurveysAsync();
        if (surveys == null)
            return NotFound("No surveys found");

        var surveyDtos = surveys.Select(survey => new SurveyTableDto
        {
            Id = survey.Id,
            Title = survey.Title,
            Description = survey.Description,
            CreatedDate = survey.CreatedDate,
            // You can easily convert Enums to strings for the frontend here!
            Status = survey.Status.ToString()
        }).ToList();
    return Ok(surveyDtos);
    }

    [HttpPost("Create", Name = "CreateSurvey")]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<SurveyDto>> CreateSurveys([FromBody] SurveyDto surveyDto)
    {
        if (surveyDto == null || string.IsNullOrEmpty(surveyDto.Title))
            return BadRequest("Invalid survey data");

        SurveyBL newSurvey = new SurveyBL(
            surveyId: 0, // ID will be generated by the database
            title: surveyDto.Title,
            description: surveyDto.Description,
            isAnonymous: surveyDto.IsAnonymous,
            isActive: surveyDto.IsActive,
            createdDate: DateTime.UtcNow
        );
        int newSurveyId =await newSurvey.Save();

        if (newSurveyId > 0)
        {
            return CreatedAtRoute("GetAllSurveys", new { id = newSurveyId}, surveyDto); // Simulate an ID generation
        }
        
        
        var createdSurvey = new SurveyDto
        {
            Id = new Random().Next(1, 1000), // Simulate an ID generation
            Title = surveyDto.Title,
            Description = surveyDto.Description
        };

        return CreatedAtRoute("GetAllSurveys", new { id = createdSurvey.Id }, createdSurvey);
    }
}